/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovaciones.reporte.util;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author pisama
 */
public enum Enums {

    PREVENTIVO("MANTENIMIENTO PREVENTIVO", "PREVENTIVO"),
    CORRECTIVO("MANTENIMIENTO CORRECTIVO", "CORRECTIVO"),
    CORRECTIVO_ETIQUETADORAS("MANTENIMIENTO CORRECTIVO ETIQUETADORAS", "CORRECTIVO_ETIQUETADORA"),
    MANTENIMIENTO_PROCESAMIENTO("MANTENIMIENTO PROCESAMIENTO", "PROCESAMIENTO"),
    MANTENIMIENTO_PREVENTIVO_IMAGEN("MANTENIMIENTO PREVENTIVO IMAGEN", "IMAGEN_PREVENTIVO"),
    MANTENIMIENTO_PREVENTIVO_FIJACION("MANTENIMIENTO PREVENTIVO FIJACION", "FIJACION_PREVENTIVO"),
    MANTENIMIENTO_EXTERIORES("MANTENIMIENTO EXTERIORES", "EXTERIORES"),
    MANTENIMIENTO_SUMINISTROS("MANTENIMIENTO SUMINISTROS", "SUMINISTROS"),
    MANTENIMIENTO_CORRECTIVO_IMAGEN("MANTENIMIENTO CORRECTIVO IMAGEN", "IMAGEN_CORRECTIVO"),
    MANTENIMIENTO_CORRECTIVO_FIJACION("MANTENIMIENTO CORRECTIVO FIJACION", "FIJACION_CORRECTIVO"),
    MANTENIMIENTO_CORRECTIVO_REVELADO("MANTENIMIENTO CORRECTIVO REVELADO", "REVELADO"),
    MANTENIMIENTO_ALIMENTACION("TIPO MANTENIMIENTO ALIMENTACION", "ALIMENTACION"),
    MANTENIMIENTO_OTROS("MANTENIMIENTO OTROS", "OTROS"),
    TIPO_REPORTE_DIAGNOSTICO("REPORTE DIAGNOSTICO", "DIAGNOSTICO"),
    TIPO_REPORTE_REPARACION("REPORTE REPARACION", "REPARACION"),
    TIPO_REPORTE_CONTADORES("REPORTE CONTADORES", "CONTADOR"),
    TIPO_REPORTE_ETIQUETADORAS("REPORTE ETIQUETADORAS", "ETIQUETADORAS"),
    TIPO_REPORTE_TRITURADORAS("REPORTE TRITURADORAS", "TRITURADORAS"),
    TIPO_REPORTE_SCANNERS("REPORTE SCANNERS", "SCANNERS"),
    TIPO_REPORTE_MONITORES("REPORTE MONITORES", "MONITORES"),
    TIPO_REPORTE_ECU("ECU911", "ECU911"),
    TIPO_REPORTE_ECU911("REPORTE_ECU", "REPORTE_ECU"),
    TIPO_REPORTE_GENERICO("REPORTE GENERICO", "REPORTE_GENERICO"),
    ECU911_ADMINISTRACION("ADMINISTRACION REPORTES ECU911", "ECU911_ADMINISTRACION"),
    TIPO_IMPRESORA_COPIADORA("IMPRESORA/COPIADORA", "IMP./COP."),
    TIPO_NOTA_EGRESO("NOTAS DE EGRESO", "NE"),
    TIPO_EGRESO_BODEGA("EGRESOS DE BODEGA", "EB"),
    TIPO_EGRESO_CONTRATO("EGRESOS DE CONTRATOS", "EC"),
    TIPO_DEVOLUCION_BODEGA("DEVOLUCION DE BODEGA", "DEV"),
    ESTADO_PROCESO_INGRESADO("INGRESADO", "INGRESADO"),
    ESTADO_PROCESO_RESERVADO("RESERVADO", "RESERVADO"),
    ESTADO_PROCESO_SOLICITADO("SOLICITADO", "SOLICITADO"),
    ESTADO_PROCESO_DESPACHADO("DESPACHADO", "DESPACHADO"),
    ESTADO_PROCESO_DEVUELTO("DEVUELTO", "DEVOLUCIÓN"),
    TIPO_INGRESO_LOCAL("LOCAL", "LOCAL"),
    TIPO_INGRESO_IMPORTACION("IMPORTACION", "IMPORTACION"),
    TIPO_PRODUCTO_EQUIPO("EQUIPO", "EQUIPO"),
    TIPO_PRODUCTO_REPUESTO("REPUESTO", "REPUESTO"),
    TIPO_PRODUCTO_ACCESORIO("ACCESORIO", "ACCESORIO"),
    TIPO_PRODUCTO_SUMINISTRO("SUMINISTRO", "SUMINISTRO"),
    //    IMPRESORA_DIAGNOSTICO("IMPRESORA DIAGNOSTICO", "DIAGNOSTICO"),
    //    IMPRESORA_REPARACION("IMPRESORA REPARACION", "REPARACION"),
    //    IMPRESORA_CONTADORES("IMPRESORA CONTADORES", "CONTADOR"),
    //    
    //    SCANNER_DIAGNOSTICO("SCANNER DIAGNOSTICO", "DIAGNOSTICO"),
    //    SCANNER_REPARACION("SCANNER REPARACION", "REPARACION"),
    //    
    //    ETIQUETADORA_DIAGNOSTICO("ETIQUETADORA DIAGNOSTICO", "DIAGNOSTICO"),
    //    ETIQUETADORA_REPARACION("ETIQUETADORA REPARACION", "REPARACION"),
    //    
    //    MONITOR_DIAGNOSTICO("VIDEO DIAGNOSTICO", "DIAGNOSTICO"),
    //    MONITOR_REPARACION("VIDEO REPARACION", "REPARACION"),
    //    
    //    DESTRUCTORA_DIAGNOSTICO("DESTRUCTORA DIAGNOSTICO", "DIAGNOSTICO"),
    //    DESTRUCTORA_REPARACION("DESTRUCTORA REPARACION", "REPARACION"),    
    //    

    ADMINISTRACION("ADMINISTRACION", "ADMINISTRACION"),
    ADMINISTRACION_REPORTES("ADMINISTRACION_REPORTES", "ADMINISTRACION_REPORTES"),
    ADMINISTRACION_ETIQUETADORAS("ETIQUETADORAS", "ADMINISTRACION_ETIQUETADORAS"),
    ADMINISTRACION_MONITORES("MONITORES", "ADMINISTRACION_MONITORES"),
    ADMINISTRACION_SCANNERS("SCANNERS", "ADMINISTRACION_SCANNERS"),
    ADMINISTRACION_TRITURADORES("TRITURADORAS", "ADMINISTRACION_TRITURADORES"),
    IMPRESION_PREVENTIVO("IMPRESION_PREVENTIVO", "IMPRESION_PREVENTIVO"),
    EXTERIOR_PREVENTVO("EXTERIOR_PREVENTVO", "EXTERIOR_PREVENTVO"),
    ELECTRICAS_PREVENTIVO("ELECTRICAS_PREVENTIVO", "ELECTRICAS_PREVENTIVO"),
    SUMINISTROS_CORRE_ETIQ("SUMINISTROS_CORRE_ETIQ", "SUMINISTROS_CORRE_ETIQ"),
    IMPRESION_CORRECTIVO("IMPRESION_CORRECTIVO", "IMPRESION_CORRECTIVO"),
    ELECTRICAS_CORRECTIVO("ELECTRICAS_CORRECTIVO", "ELECTRICAS_CORRECTIVO"),
    OTROS_CORREC_ETIQ("OTROS_CORREC_ETIQ", "OTROS_CORREC_ETIQ"),
    EXTERIOR_MONITORES_PRE("EXTERIOR_MONITORES_PRE", "EXTERIOR_MONITORES_PRE"),
    ELECTRICAS_MONITORES_PRE("ELECTRICAS_MONITORES_PRE", "ELECTRICAS_MONITORES_PRE"),
    ESTRUCTURA_MONITORES_PRE("ESTRUCTURA_MONITORES_PRE", "ESTRUCTURA_MONITORES_PRE"),
    SUMINISTRO_MONITORES("SUMINISTRO_MONITORES", "SUMINISTRO_MONITORES"),
    ESTRUCTURA_MONITORES_COR("ESTRUCTURA_MONITORES_COR", "ESTRUCTURA_MONITORES_COR"),
    ELECTRICAS_MONITORES_COR("ELECTRICAS_MONITORES_COR", "ELECTRICAS_MONITORES_COR"),
    OTROS_MONITORES("OTROS_MONITORES", "OTROS_MONITORES"),
    RODILLO_TRANSPORTE_PRE("RODILLO_TRANSPORTE_PRE", "RODILLO_TRANSPORTE_PRE"),
    EXTERIOR_SCANNER("EXTERIOR_SCANNER", "EXTERIOR_SCANNER"),
    PARTES_ELECTRICAS_SCANNER("PARTES_ELECTRICAS_SCANNER", "PARTES_ELECTRICAS_SCANNER"),
    SUMINISTROS_SCANNER("SUMINISTROS_SCANNER", "SUMINISTROS_SCANNER"),
    ELECTRICAS_SCANNER("ELECTRICAS_SCANNER", "ELECTRICAS_SCANNER"),
    MECANISMO_SCANNER("MECANISMO_SCANNER", "MECANISMO_SCANNER"),
    OTROS_SCANNERS("OTROS_SCANNER", "OTROS_SCANNER"),
    MECANISMO_TRITURADORAS_PRE("MECANISMO_TRITURADORAS_PRE", "MECANISMO_TRITURADORAS_PRE"),
    EXTERIOR_TRITURADORAS("EXTERIOR_TRITURADORAS", "EXTERIOR_TRITURADORAS"),
    ELECTRICAS_TRITURADORAS_PRE("ELECTRICAS_TRITURADORAS_PRE", "ELECTRICAS_TRITURADORAS_PRE"),
    SUMINISTRO_TRITURADORAS("SUMINISTRO_TRITURADORAS", "SUMINISTRO_TRITURADORAS"),
    MECANISMO_TRITURADORAS_COR("MECANISMO_TRITURADORAS_COR", "MECANISMO_TRITURADORAS_COR"),
    ELECTRICAS_TRITURADORAS_COR("ELECTRICAS_TRITURADORAS_COR", "ELECTRICAS_TRITURADORAS_COR"),
    OTROS_TRITURADORES("OTROS_TRITURADORES", "OTROS_TRITURADORES"),
    PARAMETRO_TIPO_REPORTE("PARAMETRO TIPO REPORTE", "TIPO_REPORTE"),
    ESTADO_REPORTE_PROCESO("ESTADO DE REPORTE EN PROCESO", "PROCESANDO"),
    ESTADO_REPORTE_FINALIADO("ESTADO DE REPORTE FINALIZADO", "FINALIZADO"),
    ROLE_ADMIN("ROLE ADMINISTRADOR", "ROLE_ADMIN"),
    ROLE_TECNICO("ROLE TECNICO", "ROLE_TECNICO"),
    ROLE_VENTAS("ROLE VENTAS", "ROLE_VENTAS"),
    ROLE_POSTVENTAS("ROLE POSTVENTAS", "ROLE_POSTVENTAS"),
    ROLE_BODEGUERO("ROLE BODEGA", "ROLE_BODEGA"),
    ROLE_INVITADO("ROLE INVITADO", "ROLE_INVITADO"),
    PARAMETRO_ID_REPORTE("PARAMETRO ID REPORTE", "ID REPORTE"),
    PARAMETRO_MENSAJE_LOGIN("PARAMETRO MENSAJE LOGIN", "MENSAJE LOGIN"),
    ASIGNACION("ASIGNACION", "ASIGNACION"),
    REPORTE("REPORTE", "REPORTE"),
    INSTALACION("INSTALACION", "INSTALACION"),
    ESTADO_ASIGNACION_ASIGNADO("ASIGNADO", "ASIGNADO"),
    ESTADO_ASIGNACION_PREASIGNADO("PREASIGNADO", "PREASIGNADO"),
    ESTADO_ASIGNACION_ELIMINADO("ELIMINADO", "ELIMINADO"),
    PAGINA_ADMINISTRACION_REPORTE("PAGINA REPORTE", "/reportes/consultas.jsf"),
    PAGINA_ADMINISTRACION_REPORTE_WIZARD("PAGINA REPORTE", "/reportes/consultasWizard.jsf"),
    PAGINA_ADMINISTRACION_REPORTE_ECU911("PAGINA REPORTE", "/reportes/administracionecu911.jsf"),
    PAGINA_REPORTE_ECU911("PAGINA REPORTE", "/reportes/reporteecu911.jsf"),
    PAGINA_REPORTE("PAGINA REPORTE", "/reportes/reporte.jsf"),
    PAGINA_REPORTE_ETIQUETADORA("PAGINA REPORTE ETIQUETADORA", "/reportes/etiquetadoras.jsf"),
    PAGINA_REPORTE_MONITOR("PAGINA REPORTE MONITOR", "/reportes/monitores.jsf"),
    PAGINA_REPORTE_SCANNER("PAGINA REPORTE SCANNER", "/reportes/scanners.jsf"),
    PAGINA_REPORTE_TRITURADORA("PAGINA REPORTE TRITURADORA", "/reportes/trituradoras.jsf"),
    PAGINA_REPORTE_ETIQUETADORA_WIZARD("PAGINA REPORTE ETIQUETADORA", "/reportes/etiquetadorasWizard.jsf"),
    PAGINA_REPORTE_MONITOR_WIZARD("PAGINA REPORTE MONITOR", "/reportes/monitoresWizard.jsf"),
    PAGINA_REPORTE_SCANNER_WIZARD("PAGINA REPORTE SCANNER", "/reportes/scannersWizard.jsf"),
    PAGINA_REPORTE_TRITURADORA_WIZARD("PAGINA REPORTE TRITURADORA", "/reportes/trituradorasWizard.jsf"),
    PAGINA_REPORTE_NUEVA_INSTALACION("PAGINA INSTALACION NUEVA", "/instalaciones/instalacion-nueva.jsf"),
    PAGINA_ADMINISTRACION_REPORTES_INSTALACION("PAGINA INSTALACION TEMPORAL", "/instalaciones/administracion.jsf"),
    TIPO_INSTALACION("TIPO INSTALACION", "TIPO_INSTALACION"),
    INSTALACION_NUEVA("INSTALACION NUEVA", "NUEVA"),
    INSTALACION_TEMPORAL("INSTALACION TEMPORAL", "TEMPORAL"),
    INSTALACION_MEDICIONES("INSTALACION MEDICIONES", "MEDICIONES"),
    INSTALACION_CONSIDERACIONES("INSTALACION CONSDIREACIONES", "CONSIDERACIONES"),
    INSTALACION_PREGUNTAS("INSTALACION PREGUNTAS", "PREGUNTAS"),
    CODIGO_EMPRESA("CODIGO EMPRESA", "CODE_ENTERPRISE"),
    DATOS_REEMPLAZO("DATOS A REEMPLAZAR", "DATOS_REEMPLAZO"),
    DATOS_TEMPORAL("DATOS TEMPORALES", "DATOS_TEMPORAL"),
    MAIL_ADDRESS("MAIL_ADDRESS", "MAIL_ADDRESS"),
    MAIL_PASS("MAIL_PASS", "MAIL_PASS"),
    MAIL_SMTP_HOST("MAIL_SMTP_HOST", "MAIL_SMTP_HOST"),
    MAIL_SMTP_PORT("MAIL_SMTP_PORT", "MAIL_SMTP_PORT"),
    MAIL_STATUS("MAIL_STATUS", "MAIL_STATUS"),
    MANTENIMIENTO_PREVENTIVO("MANTENIMIENTO_PREVENTIVO", "P"),
    MANTENIMIENTO_CORRECTIVO("MANTENIMIENTO_CORERCTIVO", "C");

    private final String propertyName; //Nombre del estado (propiedad)
    private final String value; // Valor del estado
    private static final Map<String, Enums> lookup = new HashMap<>();

    Enums(String propertyName, String value) {
        this.propertyName = propertyName;
        this.value = value;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public String getValue() {
        return value;
    }

    static {
        for (Enums d : Enums.values()) {
            lookup.put(d.getValue(), d);
        }
    }

    public static Enums get(String key) {
        return lookup.get(key);
    }

}
